# Site settings
baseURL = 'https://mondayflowers.org/'
languageCode = 'en-US'
title = 'MONDAY Flowers'
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2024 Monday Flowers"

[params]

# Metadata for search engines and social sharing
author = "Monday Flowers"
description = "subscription flower delivery."
shareImage = "images/social.jpg"

# Favicon
favicon = "favicon.ico"

# Section - Visual
[params.visual]

# Image
[params.visual.image]
enable = true
file = "images/mondayflowers.jpg"
position = "center"

# Video
[params.visual.video]
enable = false
mute = true
file = "videos/background.mp4"
# youtubeId = "dk9uNWPP7EA"


# Links
#
# Links List #1
[[params.links]]
[params.links.list1]
heading = "Connect"

[[params.links.list1.link]]
text = "Line"
url = "https://line.me/ti/p/BbOeGJwsJM"
new_tab = true                          # new tab

[[params.links.list1.link]]
text = "Messenger"
url = "#"
new_tab = true

# Links List #2
[[params.links]]
[params.links.list2]
heading = "Social"

[[params.links.list2.link]]
text = "Instagram"
url = "https://www.instagram.com/getmondayflowers"
new_tab = true

[[params.links.list2.link]]
text = "Facebook"
url = "https://www.facebook.com/share/Sv37G2aozrhYnoGh/"
new_tab = true


# Links List #3
[[params.links]]
[params.links.list3]
heading = "Early Access"

[[params.links.list3.link]]
text = "subscribe now"
url = "https://buy.stripe.com/28ofZQe0sdmDfjW4gg"

# [[params.links.list3.link]]
# text = "Link Two"
# url = "#"

# The original template is licensed via the template author's website: https://onepagelove.com/split
# License has been purchesed by Yudame Inc.
